### ISSUE TITLE
Ophom doesn't recognize Ikea Tradfri outlets on a Hue bridge

### ISSUE THREAD

**Issue by simingx** [Salamafet/ophom#10]
Ikea Tradfri outlets don't show up on a Hue bridge in Ophom, but are otherwise controllable. Could this functionality be added?

**Comment by Salamafet** [comment]
If you are comfortable using the Hue API can you send me your configuration ?

I will quickly create a feature for extract configuration from Ophom.

**Comment by simingx** [comment]
Sure, I’ll extract it for you when the feature becomes available.

**Comment by Salamafet** [comment]
The config extractor is ready

![](https://i.imgur.com/AgJCm3q.png)

Please update Ophom and send me your config file.

**Comment by simingx** [comment]
Hi,
I've extracted the config but would prefer not to post it here as there is a lot of private data inside, is there a way I can send it to you privately?

**Comment by Salamafet** [comment]
Here is my private file server.
https://file.zorio.fr/s/onCDLStAGoptoW4

With this link, only deposit are allowed.

**Comment by simingx** [comment]
Done :)
By the way, it keeps asking me to update even though I've already done so.
Is it an Octoprint or Ophom issue?

**Comment by Salamafet** [comment]
Thx

Oh my fault. I have forgot to modify the version in my code.

I review your config file and come back to you.

**Comment by Salamafet** [comment]
I have push an update. 

Keep me update

**Comment by simingx** [comment]
So far so good, I’ll try it with a print and update the status here after it (hopefully) completes without incident :)

**Comment by simingx** [comment]
Hi, it just completed a print and turned off the outlet just like it's supposed to :) Thanks!

**Comment by Salamafet** [comment]
Great ! 
Thanks for your feedback.
