### ISSUE TITLE
Maximum temperature

### ISSUE THREAD

**Issue by locki8383** [Salamafet/ophom#12]
Hello,

due to security reasons is it possible to implement not only the minimum but as well the maximum temperature for shutdown. Just in case of a meltdown of transistors or something else.

Thanks in advance

Locki

**Comment by Salamafet** [comment]
Hi Locki,

This is a good idea. I will check the documentation of OctoPrint to know the offered possibilities.

**Comment by Ranney1** [comment]
Yeah, that would be great! And, if possible, maybe it is an option to read the GCODE and if an M112 is send or if the connection is lost that the power can be turned off? Thanks for the great plugin!

**Comment by Salamafet** [comment]
@Ranney1 can you create a new issue for the GCODE support ?
And please add more details. I'm not comfortable with GCODE command.

I adding connection lost action in my todo list.

**Comment by Ranney1** [comment]
@Salamafet Of course, i will add a new 'issue'. Thanks for your time for the plugin!

And about the GCODE support, if a user want to terminate the printer instantly, they can also send the GCODE: 'M112' to the printer. It will turn itself off directly. So my idea was:
- If an thermal runaway is detected, the printer will turn itself off ==> Connection is lost ==> Turn off power
- If an plugin detects abnormality (extreme temps for example) it will send an M112 code to the printer ==> Turn off power
- If an technical fault makes the printer is not responding anymore ==> Connection lost ==> Turn off power.
-Or an technical fault makes the printer cannot stop heating ==> M112 is send ==> Disconnect power.

I think that this can make 3D printing a little bit safer!

**Comment by Salamafet** [comment]
Currently I'm working on the security options.
What is the common critical temperature for a nozzle and a bed?

**Comment by Ranney1** [comment]
Hi,

Thanks for all your work!! The max temp of the nozzle is for every printer/setup different. For bowden tube machines the max temp that the bowden tube can handle for long time is around 225 celcius. A little bit warmer (230-245) is possible but this will impact the life of de bowden tube. For direct drives it is what the material of the hotend can handle (examples:  https://e3d-online.dozuki.com/Wiki/Maximum_temperature_for_the_Chimer). For me, as 'home user' I don't want 'to see a temp higher than 230 celcius.
As a reference, I think that higher than 260 is not for the 'normal' user. (Common materials: https://m.all3dp.com/2/the-best-printing-temperature-for-different-filaments)


Can you make the max temp configurable?

**Comment by Ranney1** [comment]
Ø, sorry, I didn't answer your 2nd question. I think that it is the same for the heated bed. My printer cannot handle a higher temp as 110 celcius for the bed. But.. I do not use materials that needs a higher temp than 65 celcius. So, if my bed will get a temp of 70 celcius, there is absolutely something wrong..

**Comment by Salamafet** [comment]
Ok thanks

250°C for the nozzle and 80°C for the bed seems to be good as default security shutdown.
In the worst cases of a user use higher temperature, the printer will shutdown before print begins (except if the temperature is modified by the gcode along the way).

**Comment by Salamafet** [comment]
New release with the maximum temperature option :)
Please reopen this thread if you have an issue with this release.

**Comment by locki8383** [comment]
Perfect!!! Thanks for modifiing this plugin. This is exactly what every 3D printer user should use to avoid bad surprises. Now it feels a bit safer to use my printer. Thank you very much.
