### ISSUE TITLE
Shutdown on exceeding temperature X (or printtemp + X)

### ISSUE THREAD

**Issue by wuenschd84** [Salamafet/ophom#15]
I recently had an issue with a FET on the Trigorilla - the FET went to ON - so the temperature exceeded >300°C 
I'd like to have an option like this to prevent fire hazzards :)

**Comment by Salamafet** [comment]
Same demand here https://github.com/Salamafet/ophom/issues/12

I'm working on it.

**Comment by Salamafet** [comment]
https://github.com/Salamafet/ophom/issues/12#issuecomment-687064551
