### ISSUE TITLE
GCODE reading an option?

### ISSUE THREAD

**Issue by Ranney1** [Salamafet/ophom#16]
As requested in [Issue 12](https://github.com/Salamafet/ophom/issues/12)
I think that it can be great if the plugin can 'read' the current GCODE send to the printer en act on an 'M112' 

Background: if a user want to terminate the printer instantly, they can also send the GCODE: 'M112' to the printer. It will turn itself off directly. (This can also be triggerd by an plugin). So my idea was:

- If an thermal runaway is detected, the printer will turn itself off ==> Connection is lost ==> Turn off power
- If an plugin detects abnormality (extreme temps for example) it will send an M112 code to the printer ==> Turn off power
- If an technical fault makes the printer is not responding anymore ==> Connection lost ==> Turn off power.
- Or an technical fault makes the printer cannot stop heating ==> M112 is send ==> Disconnect power.

I think that this can make 3D printing a little bit safer!

**Comment by Salamafet** [comment]
I have made some test with the M112 code. 

When I send this code to my printer, the connection is immediately interrupted. Is it the same way for all printers ?

**Comment by Ranney1** [comment]
Hi,

Yes. Al marlin based printers will:
-if 'emergency parcer enabled' directly turn off the motors, heaters and it will disconnect to host. Only a reboot wil make printing possible again.
- if emergency parcer is not enabled, the printer will stop directly when the 'M112' code can be send (space in buffer). This means normally after some seconds.

**Comment by Ranney1** [comment]
A little bit more info: https://marlinfw.org/docs/gcode/M112.html

**Comment by Salamafet** [comment]
Ok thanks, I will add an option for cutting down power when the connection is interrupted.

**Comment by Ranney1** [comment]
Great! 👍
Really happy with this option! 👌

**Comment by Salamafet** [comment]
New release with the lost connection and M112 shutdown option :)
Please reopen this thread if you have an issue with this release.
