### ISSUE TITLE
Auto-connecting on power-up fails with Prusa Mini due to the delay being too short

### ISSUE THREAD

**Issue by flxs** [Salamafet/ophom#25]
First of all, great plugin, thanks for making this available!

The _Try to connect to printer after power On the plug_ option has a fixed delay of 5 seconds. However, the Prusa Mini needs a bit more than 5 seconds to power up (more like 10-15), because it runs a basic self-check before allowing serial connections, so the connection attempts always fail (and don't get retried).

It would be really great to either 
- be able to set the delay to something like 10-15 seconds, or ...
- have ophom retry a couple of times on connection failure.

**Comment by Salamafet** [comment]
I have the same issue since few days.
I will patch this as soon as possible.

**Comment by Salamafet** [comment]
New version available
https://github.com/Salamafet/ophom/releases/tag/1.3.3

You can now choose the time to wait before auto connect when printer is powered on.
Please feel free to reopen this issue if you encounter problems.
