### ISSUE TITLE
Problem during M600

### ISSUE THREAD

**Issue by Ranney1** [Salamafet/ophom#31]
Dear,

When issuing an M600 (manually or when the filament sensor is triggered). the printer nozzle is parked and the nozzle is cooling down while waiting for user action. Ophom is interpretating this as an succesful finished print and cut the power.

Any idea how to fix this problem?
Thanks for help (again!)

**Comment by Salamafet** [comment]
Hello,

Ophom start to watch temperature for shutdown only when this different event are triggered: 
- PrintDone
- EStop
- Disconnected
- Shutdown

Do you know if this event are triggered when M600 is issuing ?

Can you check this issue https://github.com/OctoPrint/OctoPrint/issues/3699. Maybe you can find an answer.

**Comment by Ranney1** [comment]
Thanks for your fast response! Please close this issue for now.

After investigation, we found out that 60-90 sec after issuing an m600 command the printer is rebooting. I think a watchdog problem. For now I think that the interuption of the serial connection was triggering the power off (and not the temp drop). But do not now it for sure. Have to fix the m600 issue first. Sorry for this. I send you an update when I know more!

**Comment by Salamafet** [comment]
No problem 😊

Feel free to reopen.
