### ISSUE TITLE
Shut down after hitting print Button

### ISSUE THREAD

**Issue by CR6-SE** [Salamafet/ophom#32]
Hi,

after the new Update of Ophom i have the bug, that after i hit the print button in OctoPrint the Smart Switch cuts the Energy.

Best regards

Arne

**Comment by Salamafet** [comment]
Hi,

I suppose you have trying with different gcode file ?

The last update add the possibility to set the timer to auto connect to the printer after power on the plug. Are you sure the printer is correctly connected when you start a print ?
By default, if a print is currently running and the printer is not connected, the plug is powred off for security reason. 
Can you try to disable this option in the Ophom configuration ?

**Comment by CR6-SE** [comment]
Okay it was my fault. First time printing ABS and the values for emergency shutdown were too low. 
But i noticed one more Problem. When Octoprint restarts because i do updates for plugins etc. the switch also goes of.

And one feature would be nice. I have powered the pi with the same plug as the printer. Is it possible to shout down the pi securly and after that the plug is sitched of. 
I mean not after a print.

**Comment by Salamafet** [comment]
> When Octoprint restarts because i do updates for plugins etc. the switch also goes of.

I think after an update the printer is not connected. So the security is triggered. You can easily disable it.

> And one feature would be nice. I have powered the pi with the same plug as the printer. Is it possible to shout down the pi securly and after that the plug is sitched of.
> I mean not after a print.

This option already exist. You can choose the _Delayed Shutdown Option_. After a print done and the minimum temperature reached, the system is correctly powered off and 2 minutes later the plug is powered off too.

**Comment by CR6-SE** [comment]
Yeah i know that it works after a print. Same option in octoprint without printing would be nice. I Play arround with different plugins and that often without printing. Would be nice to have an option to shout down securly without printing.

Best regards and thank you for your help.

**Comment by Salamafet** [comment]
Oh ok, now I understand what do you want.

I don't think I will add an option like this. Ophom aims for automate the shutting down of the printer when you can't monitor it.
If you decide to shutdown your Pi, you can wait 30 seconds for manually power off the plug.

If it is a recurring request maybe I will work on this. Sorry.

**Comment by CR6-SE** [comment]
Okay that would be awesome.
