### ISSUE TITLE
Disconnect Printer Before Shutdown?

### ISSUE THREAD

**Issue by James-Coyne** [Salamafet/ophom#36]
To avoid inaccurate errors in cases where Octoprint remains live while the printer turns off, it would be nice if Ophom told Octoprint to disconnect from the printer before shutting off the plug powering it. Could this feature be added?

**Comment by Salamafet** [comment]
I can add this function but what kind of error are you talking about ?
In my case Octoprint still live every time and I have encountered no error.

**Comment by James-Coyne** [comment]
Octoprint will report a connection timeout error when the plug and printer are shut off. Other plugins that monitor prints and send messages to external services can also interpret this as a failure.

**Comment by Salamafet** [comment]
This is a good reason 👍 

I add this to my todo.

**Comment by Salamafet** [comment]
Done !

USB is now correctly disconnected before shutdown.
Reopen this issue if you have any problem with this update.

And sorry for the delay.
