### ISSUE TITLE
Unintentinal Power-Off on Server Restart

### ISSUE THREAD

**Issue by rene-mt** [Salamafet/ophom#38]
Since I installed Ophom - which for the actual purpose works fine - I have the problem that my Osram/HUE switch is powered off on a restart of Octoprint after installing/updating plug-ins.

Could it be that the plugin receives a `Shutdown` event in case of a server restart and therefore executes the power-off here:

    [...]
    elif(event == "Shutdown"):
      if(self._settings.get(['auto_off']) == True):
        self.turn_off()
    [...]
([\_\_init\_\_.py](https://github.com/Salamafet/ophom/blob/5e33ee57b0ed05797c6ff62cfa0dca8f3f256898/octoprint_phom/__init__.py#L267))

**Comment by Salamafet** [comment]
This line was rework by @bitkeeper.

I will see if it is possible to know if an update is in progress to avoid extinction.
And sorry for the late response

**Comment by bitkeeper** [comment]
@rene-mt:  Based on the [plugin events](https://docs.octoprint.org/en/master/events/index.html) no difference can be made between a octoprint software restart, system reboot or system shutdown. All will get the "Shutdown" event.  Only on system shutdown a power-off is acceptable.

Disable the power off on shutdown in #39 untill clear how to detect the correct situation.

**Comment by Salamafet** [comment]
Thanks @bitkeeper for the fix.

A new release is out
