### ISSUE TITLE
Ophom together with Telegram plugin

### ISSUE THREAD

**Issue by Tonitom** [Salamafet/ophom#41]
hi,
on Octoprint runs in parallel the Telegram plugin, when the print is finished, no message is sent. But when the printer has reached its shutdown temperature and Ophom turns off the socket, then I get the ready message on Telegram

**Comment by Salamafet** [comment]
Hi,
The Ophom plugin doing is job right ? 
Please create an issue on the Telegram plugin first and wait for a conclusion.
