### ISSUE TITLE
Setup with multiple bridges

### ISSUE THREAD

**Issue by cmsj** [Salamafet/ophom#45]
Hi!

I realise this is very much an unusual situation, but I have two Hue bridges and Ophom only offers pairing with the first one returned by the meethude discovery service. would it be possible to have the UI present a dropdown of all discovered bridges?

Thanks!

**Comment by docNeptun** [comment]
I have a similar situation, with one Hue bridge and one Deconz-Instance that mimics the characteristics of a hue bridge v1 ... so we're at least two ;-)

**Comment by Salamafet** [comment]
Hi guys,

I will work on it as soon as possible

**Comment by Salamafet** [comment]
The update is now released 
https://github.com/Salamafet/ophom/releases/tag/1.4.0

I don't have multiple bridge, so my tests is not perfect. If you found a bug, please come back to me.

**Comment by docNeptun** [comment]
Hi, my deconz/Conbee server unfortunately is not being found.. probably because it does not listen to port 80 but port 4530..

**Comment by Salamafet** [comment]
Can you see it at this address [https://discovery.meethue.com/](https://discovery.meethue.com/) ?

Ophom use this API for discovering Bridge.

**Comment by docNeptun** [comment]
> Can you see it at this address https://discovery.meethue.com/ ?
> 
> Ophom use this API for discovering Bridge.

Unfortunately, only the HUE bridge shows up there.. :(

**Comment by docNeptun** [comment]
I have found [this ressource](https://github-wiki-see.page/m/dresden-elektronik/deconz-rest-plugin/wiki/Bridge-Discovery) regarding discovery process and the differences between HUE and deCONZ... respectively ZigBee bridges from other vendors...

https://github-wiki-see.page/m/dresden-elektronik/deconz-rest-plugin/wiki/Bridge-Discovery

**Comment by Salamafet** [comment]
Can you see your deCONZ at [https://phoscon.de/discover](https://phoscon.de/discover) ?

I can add a form to manually enter an IP address and port, but if deCONZ did not have the same API request as Hue Bridge, nothing will work.

For a different port, I need to make a rework of Ophom

**Comment by docNeptun** [comment]
> Can you see your deCONZ at https://phoscon.de/discover ?
> 
> I can add a form to manually enter an IP address and port, but if deCONZ did not have the same API request as Hue Bridge, nothing will work.
> 
> For a different port, I need to make a rework of Ophom

Yes, I can see the bridge:

`[{"id":"002xxxxxxxxxxx","internalipaddress":"192.168.178.50","macaddress":"002xxxxxxxxx","internalport":4530,"name":"Phoscon","publicipaddress":"217.81.xxx.xx"}] `

**Comment by Salamafet** [comment]
I've checked the API of deCONZ, and it's seemed to be the same as Philips Hue Bridge.

I will start working on adding the deCONZ discovering service to Ophom.

**Comment by Salamafet** [comment]
Done 👍 
https://github.com/Salamafet/ophom/releases/tag/1.4.1

@docNeptun I'm waiting for your feedback. If everything working great, I will edit the Octoprint plugin page to add the deCONZ support.

**Comment by docNeptun** [comment]
Hi, thanks for your efforts!!!
Good news: it discovered multiple bridges and let me choose deconz,
bad news: I was not able to do a successful pairing.

I'm out of my wits here, sorry.  I don't even know how to debug or read error logs without step-by-step instruction.
Did you take into consideration the different port(s) - 4530 - that my specific deconz instance listens to?

thanks again.

**Comment by Salamafet** [comment]
I have forgotten to add a different port support 😅
My bad.

Here is another new release 
https://github.com/Salamafet/ophom/releases/tag/1.4.2

**Comment by docNeptun** [comment]
> I have forgotten to add a different port support 😅
> My bad.
> 
> Here is another new release
> https://github.com/Salamafet/ophom/releases/tag/1.4.2

yep, that did the job. I successfully paired the bridge and configured my osram smart+ plug :-)
thank you so much!!!!!

**Comment by Salamafet** [comment]
Great news.

Thanks for your feedback. 👍
