### ISSUE TITLE
"Plug" button in the top menu looks clickable, but seems to do nothing

### ISSUE THREAD

**Issue by MPFGlaser** [Salamafet/ophom#5]
When hovering the cursor over the "plug" icon in the top menu bar the background changes colour as if it is a functional button. However, the cursor itself does _not_ change from an arrow to a click-hand.
While I'm not sure if this is a bug or an (attempted) unintended use of the icon, my first instinct would be to click the plug to turn the Hue plug/printer on while it is in the "off" state.
Using version 1.1.0 of OPHOM and version 1.4.2 of Octoprint

**Comment by Salamafet** [comment]
I will fix that as soon as possible

Thanks

**Comment by Salamafet** [comment]
Fixed in https://github.com/Salamafet/ophom/pull/7 !

Update and go back to me if the problem persist.
