### ISSUE TITLE
Ophom finds bridges old IP

### ISSUE THREAD

**Issue by Jese44** [Salamafet/ophom#50]
Hey, so i decided to change my network into VLANs and moved hue to another one. now Ophom only finds the bridges old IP (it has been changed and checked that the hue truly has a new IP) and when applying the found (wrong) IP it is succesfully added, but obviously it doesnt work. I'm not that sure wether the IP is jammed in some config on Octoprint or are my firewall rules messed up... Any help would be appreciated

**Comment by Jese44** [comment]
Update: added firewall rule to allow from HUE to OP but no luck with that..

**Comment by Salamafet** [comment]
Hi,
For finding the bridge IP, Ophom use the official discover API of Philips Hue at this address : https://discovery.meethue.com/
Is the IP correct on this service?

**Comment by Salamafet** [comment]
Any update about this ?

**Comment by Jese44** [comment]
It seems to be working now, i had problems on setting VLAN IP on my switch and most likely it caused messing IPs up on ophom-hue

**Comment by Salamafet** [comment]
Thanks for your feedback
