### ISSUE TITLE
Ophom not working with Octoprint 1.8.3 or newer

### ISSUE THREAD

**Issue by Martin-Ox** [Salamafet/ophom#57]
Hi all,
From yesterday on, the Hue is not able to pair to the plugin.
I have done a factory reset on the Hue, added all the lights and power plug as before.
Is enabled for controling outside of the house.
But no luck with nieghter this plug in or other plugin's for the Hue. 
Is there anything I can do or is there something changed in the Octoprint code or so ?
I have the latest release of Octoprint running.(1.8.3)

Thanks in advance

**Comment by Martin-Ox** [comment]
After reverting to Octoprint 1.8.2 it works fine again.
So it's an issue with 1.8.3 and higher to this plugin

**Comment by Salamafet** [comment]
Hi Martin,

Thanks for your issue.
According to the 1.8.3 changelog, there is a new security feature. I will work on a patch tomorrow if time allows me.

**Comment by Martin-Ox** [comment]
Thanks !
I will stay with 1.8.2 then for now, awayting the patch somewhere in the next couple of days.

**Comment by Salamafet** [comment]
It's done!

Please update and give me a feedback :)

**Comment by RickBulthuis** [comment]
I used the new update, 1.5.0 gives the bug, but 1.5.1 fixed it. Great work. note: in the plugin manager of octoprint was the plugin 1.5.1 not visible

**Comment by Salamafet** [comment]
Thanks for your feedback Rick :+1: 
The update can take several hours to be available in Octoprint.

I consider this issue as resolved
