### ISSUE TITLE
Hue Light bulb

### ISSUE THREAD

**Issue by hmouridsen** [Salamafet/ophom#6]
Hi

I really enjoy this plugin, as it’s so useful turning off my printer, after a safe cooldown.

However I would wish for control over a second hue device - like a bulb. I’m using a light strip in my enclosure, so it would be nice, if I light would be off together with the printer.

Thanks

**Comment by Salamafet** [comment]
Hi @hmouridsen,

Thanks for your feedback. I will study your request.

**Comment by Salamafet** [comment]
I have just push a new release for creation of Hue Rules on the bridge.
I hope all will working well.

I close this issue. If you have any problem you can reopen it.

**Comment by hmouridsen** [comment]
Thanks a lot - it's just so cool, and it works very well - awesome plugin!

**Comment by Salamafet** [comment]
Happy to read this.

Thanks for your feedback and thanks for your support.
