### ISSUE TITLE
Delayed power off description

### ISSUE THREAD

**Issue by Unzensiert** [Salamafet/ophom#62]
I struggle to get the delayed power off to work, and the documenation doesnt say what command should be added where exactly. Can you update the description on what needs to be added (i assume at Settings -> Server -> Commands -> "Shutdown system" )

**Comment by Salamafet** [comment]
Hi,

The shutdown command depends on your operating system. You need to find the right command for your OS and paste it in `Shutdown system`.

There are a ton of OS with different versions. I can't create a list for assuming all shutdown commands. This is why the command is not registered by default in Octoprint and not in official documentation.

**Comment by Unzensiert** [comment]
Ok, i understand that. I though I need a special command for the 2 minute delay option - because the plug doesnt turn off with the delay option (with the other it does).

**Comment by Salamafet** [comment]
Maybe the plug doesn't turn off because Ophom can't execute the shutdown command.

In a normal way, Ophom executes the shutdown command after passing the minimum temp. After the command executed, the timer (default 2 minutes) start. After this time, the plug is powered off by the bridge.
