### ISSUE TITLE
no plug (bulb) detected

### ISSUE THREAD

**Issue by f8lerror** [Salamafet/ophom#63]
Was instructed by the plugin to copy my config and submit a new issue

[hue_config.txt](https://github.com/Salamafet/ophom/files/12243079/hue_config.txt)

**Comment by Salamafet** [comment]
Hi,
I can’t see any plug in your bridge configuration.
Have you fully understood the purpose of this plugin?

**Comment by f8lerror** [comment]
I thought I did, I read back through it again and realized my mistake. I apologize for the confusion.

**Comment by Salamafet** [comment]
No problem 🙂
