### ISSUE TITLE
Bridge Does not show up

### ISSUE THREAD

**Issue by Itsememario** [Salamafet/ophom#65]

**Comment by Itsememario** [comment]
Oopsie forgot description so imma ad this here:

The bridge simply does not show up in da plugin.
Do I have to connect octoprint via/LAN? 
-Charged

**Comment by Salamafet** [comment]
Hi,

Yes, the bridge needs to be on the same subnet, depending on your network configuration.
The plugin check this link to auto-discover the Bridge https://discovery.meethue.com/.
