### ISSUE TITLE
Changing Plug after Initial Setup / Disconnect Bridge

### ISSUE THREAD

**Issue by stitchbit** [Salamafet/ophom#66]
Hi,

there seems to be no way to change the plug used for switching on/off the printer once it has been set up.

Also it would be nice to disconnect from a hue bride in case you move to another bridge.

**Comment by stitchbit** [comment]
As I had to use another plug, I tried to do the connecting process again by removing all plugin data. Did not work, Then I removed the ophom plugin an reinstalled it.

Pressing the search bridge button starts the discovery but than noting more happend. It seems, that some kind of error occurred, as the api request gets a 500. But there is nothing in the logs.

**Comment by Salamafet** [comment]
Hi,

Yes, the solution is to clear plugin data.

Does your bridge appear on this URL: [https://discovery.meethue.com/](https://discovery.meethue.com/)

**Comment by stitchbit** [comment]
Yes, both bridges show up. But somehow wiping the data did not help. Even after  reinstalling Bridge discovery failes with an internal server error.

**Comment by stitchbit** [comment]
I tried to record the request, but this time (date one day later than removal) it worked. Bridges show up and was able to choose the other plug. I have no idea why. Yesterday I tried data removal and reinstallation several times, always with a server error 500.

**Comment by Salamafet** [comment]
Maybe caused by meethue server.
After too many requests to discovery.meethue.com, the server stops responding (like a ban).
I didn't manage this kind of error in my code.

So is your issue solved ?

**Comment by stitchbit** [comment]
Yes, this issue is solved. 
Thank you!
